// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HealthzOKCode is the HTTP code returned for type HealthzOK
const HealthzOKCode int = 200

/*HealthzOK Successful Operation

swagger:response healthzOK
*/
type HealthzOK struct {
}

// NewHealthzOK creates HealthzOK with default headers values
func NewHealthzOK() *HealthzOK {

	return &HealthzOK{}
}

// WriteResponse to the client
func (o *HealthzOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// HealthzMethodNotAllowedCode is the HTTP code returned for type HealthzMethodNotAllowed
const HealthzMethodNotAllowedCode int = 405

/*HealthzMethodNotAllowed Invalid input

swagger:response healthzMethodNotAllowed
*/
type HealthzMethodNotAllowed struct {
}

// NewHealthzMethodNotAllowed creates HealthzMethodNotAllowed with default headers values
func NewHealthzMethodNotAllowed() *HealthzMethodNotAllowed {

	return &HealthzMethodNotAllowed{}
}

// WriteResponse to the client
func (o *HealthzMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
