// Code generated by go-swagger; DO NOT EDIT.

package note

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/evoke365/webserver/models"
)

// NewAddNoteParams creates a new AddNoteParams object
// no default values defined in spec.
func NewAddNoteParams() AddNoteParams {

	return AddNoteParams{}
}

// AddNoteParams contains all the bound params for the add note operation
// typically these are obtained from a http.Request
//
// swagger:parameters AddNote
type AddNoteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the data of the note
	  Required: true
	  In: body
	*/
	Body *models.AddNoteRequest
	/*authenticated token
	  Required: true
	  In: header
	*/
	Token strfmt.UUID
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddNoteParams() beforehand.
func (o *AddNoteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.AddNoteRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}
	if err := o.bindToken(r.Header[http.CanonicalHeaderKey("token")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindToken binds and validates parameter Token from header.
func (o *AddNoteParams) bindToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("token", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("token", "header", raw); err != nil {
		return err
	}

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("token", "header", "strfmt.UUID", raw)
	}
	o.Token = *(value.(*strfmt.UUID))

	if err := o.validateToken(formats); err != nil {
		return err
	}

	return nil
}

// validateToken carries on validations for parameter Token
func (o *AddNoteParams) validateToken(formats strfmt.Registry) error {

	if err := validate.FormatOf("token", "header", "uuid", o.Token.String(), formats); err != nil {
		return err
	}
	return nil
}
