// Code generated by go-swagger; DO NOT EDIT.

package note

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddNoteOKCode is the HTTP code returned for type AddNoteOK
const AddNoteOKCode int = 200

/*AddNoteOK successful operation

swagger:response addNoteOK
*/
type AddNoteOK struct {
}

// NewAddNoteOK creates AddNoteOK with default headers values
func NewAddNoteOK() *AddNoteOK {

	return &AddNoteOK{}
}

// WriteResponse to the client
func (o *AddNoteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AddNoteBadRequestCode is the HTTP code returned for type AddNoteBadRequest
const AddNoteBadRequestCode int = 400

/*AddNoteBadRequest Invalid request body supplied

swagger:response addNoteBadRequest
*/
type AddNoteBadRequest struct {
}

// NewAddNoteBadRequest creates AddNoteBadRequest with default headers values
func NewAddNoteBadRequest() *AddNoteBadRequest {

	return &AddNoteBadRequest{}
}

// WriteResponse to the client
func (o *AddNoteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AddNoteUnauthorizedCode is the HTTP code returned for type AddNoteUnauthorized
const AddNoteUnauthorizedCode int = 401

/*AddNoteUnauthorized Unauthorised user credentials

swagger:response addNoteUnauthorized
*/
type AddNoteUnauthorized struct {
}

// NewAddNoteUnauthorized creates AddNoteUnauthorized with default headers values
func NewAddNoteUnauthorized() *AddNoteUnauthorized {

	return &AddNoteUnauthorized{}
}

// WriteResponse to the client
func (o *AddNoteUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// AddNoteInternalServerErrorCode is the HTTP code returned for type AddNoteInternalServerError
const AddNoteInternalServerErrorCode int = 500

/*AddNoteInternalServerError internal error

swagger:response addNoteInternalServerError
*/
type AddNoteInternalServerError struct {
}

// NewAddNoteInternalServerError creates AddNoteInternalServerError with default headers values
func NewAddNoteInternalServerError() *AddNoteInternalServerError {

	return &AddNoteInternalServerError{}
}

// WriteResponse to the client
func (o *AddNoteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
