// Code generated by go-swagger; DO NOT EDIT.

package note

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteNoteOKCode is the HTTP code returned for type DeleteNoteOK
const DeleteNoteOKCode int = 200

/*DeleteNoteOK Successful Operation

swagger:response deleteNoteOK
*/
type DeleteNoteOK struct {
}

// NewDeleteNoteOK creates DeleteNoteOK with default headers values
func NewDeleteNoteOK() *DeleteNoteOK {

	return &DeleteNoteOK{}
}

// WriteResponse to the client
func (o *DeleteNoteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteNoteBadRequestCode is the HTTP code returned for type DeleteNoteBadRequest
const DeleteNoteBadRequestCode int = 400

/*DeleteNoteBadRequest Invalid request data supplied

swagger:response deleteNoteBadRequest
*/
type DeleteNoteBadRequest struct {
}

// NewDeleteNoteBadRequest creates DeleteNoteBadRequest with default headers values
func NewDeleteNoteBadRequest() *DeleteNoteBadRequest {

	return &DeleteNoteBadRequest{}
}

// WriteResponse to the client
func (o *DeleteNoteBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteNoteUnauthorizedCode is the HTTP code returned for type DeleteNoteUnauthorized
const DeleteNoteUnauthorizedCode int = 401

/*DeleteNoteUnauthorized Unauthorised user credentials

swagger:response deleteNoteUnauthorized
*/
type DeleteNoteUnauthorized struct {
}

// NewDeleteNoteUnauthorized creates DeleteNoteUnauthorized with default headers values
func NewDeleteNoteUnauthorized() *DeleteNoteUnauthorized {

	return &DeleteNoteUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteNoteUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteNoteInternalServerErrorCode is the HTTP code returned for type DeleteNoteInternalServerError
const DeleteNoteInternalServerErrorCode int = 500

/*DeleteNoteInternalServerError internal error

swagger:response deleteNoteInternalServerError
*/
type DeleteNoteInternalServerError struct {
}

// NewDeleteNoteInternalServerError creates DeleteNoteInternalServerError with default headers values
func NewDeleteNoteInternalServerError() *DeleteNoteInternalServerError {

	return &DeleteNoteInternalServerError{}
}

// WriteResponse to the client
func (o *DeleteNoteInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
