// Code generated by go-swagger; DO NOT EDIT.

package note

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteNoteHandlerFunc turns a function with the right signature into a delete note handler
type DeleteNoteHandlerFunc func(DeleteNoteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteNoteHandlerFunc) Handle(params DeleteNoteParams) middleware.Responder {
	return fn(params)
}

// DeleteNoteHandler interface for that can handle valid delete note params
type DeleteNoteHandler interface {
	Handle(DeleteNoteParams) middleware.Responder
}

// NewDeleteNote creates a new http.Handler for the delete note operation
func NewDeleteNote(ctx *middleware.Context, handler DeleteNoteHandler) *DeleteNote {
	return &DeleteNote{Context: ctx, Handler: handler}
}

/*DeleteNote swagger:route DELETE /note/{id} note deleteNote

delete a note

delete a note of a user

*/
type DeleteNote struct {
	Context *middleware.Context
	Handler DeleteNoteHandler
}

func (o *DeleteNote) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteNoteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
