// Code generated by go-swagger; DO NOT EDIT.

package note

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetNotesParams creates a new GetNotesParams object
// no default values defined in spec.
func NewGetNotesParams() GetNotesParams {

	return GetNotesParams{}
}

// GetNotesParams contains all the bound params for the get notes operation
// typically these are obtained from a http.Request
//
// swagger:parameters getNotes
type GetNotesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*authenticated token
	  Required: true
	  In: header
	*/
	Token strfmt.UUID
	/*ID of User
	  Required: true
	  In: path
	*/
	UserID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetNotesParams() beforehand.
func (o *GetNotesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindToken(r.Header[http.CanonicalHeaderKey("token")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rUserID, rhkUserID, _ := route.Params.GetOK("userId")
	if err := o.bindUserID(rUserID, rhkUserID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindToken binds and validates parameter Token from header.
func (o *GetNotesParams) bindToken(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("token", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("token", "header", raw); err != nil {
		return err
	}

	// Format: uuid
	value, err := formats.Parse("uuid", raw)
	if err != nil {
		return errors.InvalidType("token", "header", "strfmt.UUID", raw)
	}
	o.Token = *(value.(*strfmt.UUID))

	if err := o.validateToken(formats); err != nil {
		return err
	}

	return nil
}

// validateToken carries on validations for parameter Token
func (o *GetNotesParams) validateToken(formats strfmt.Registry) error {

	if err := validate.FormatOf("token", "header", "uuid", o.Token.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindUserID binds and validates parameter UserID from path.
func (o *GetNotesParams) bindUserID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.UserID = raw

	return nil
}
