// Code generated by go-swagger; DO NOT EDIT.

// Package restapi evoke365.net OpenAPI spec
//
//  Reusable authentication server from evoke365.net
//  Terms Of Service:
//    http://swagger.io/terms/
//  Schemes:
//    https
//  Host: api.evoke365.net
//  BasePath: /v1
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: <aus.jacy@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
