// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// FindUserOKCode is the HTTP code returned for type FindUserOK
const FindUserOKCode int = 200

/*FindUserOK successful operation

swagger:response findUserOK
*/
type FindUserOK struct {
}

// NewFindUserOK creates FindUserOK with default headers values
func NewFindUserOK() *FindUserOK {

	return &FindUserOK{}
}

// WriteResponse to the client
func (o *FindUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// FindUserNoContentCode is the HTTP code returned for type FindUserNoContent
const FindUserNoContentCode int = 204

/*FindUserNoContent user not found

swagger:response findUserNoContent
*/
type FindUserNoContent struct {
}

// NewFindUserNoContent creates FindUserNoContent with default headers values
func NewFindUserNoContent() *FindUserNoContent {

	return &FindUserNoContent{}
}

// WriteResponse to the client
func (o *FindUserNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// FindUserBadRequestCode is the HTTP code returned for type FindUserBadRequest
const FindUserBadRequestCode int = 400

/*FindUserBadRequest bad request

swagger:response findUserBadRequest
*/
type FindUserBadRequest struct {
}

// NewFindUserBadRequest creates FindUserBadRequest with default headers values
func NewFindUserBadRequest() *FindUserBadRequest {

	return &FindUserBadRequest{}
}

// WriteResponse to the client
func (o *FindUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// FindUserInternalServerErrorCode is the HTTP code returned for type FindUserInternalServerError
const FindUserInternalServerErrorCode int = 500

/*FindUserInternalServerError internal error

swagger:response findUserInternalServerError
*/
type FindUserInternalServerError struct {
}

// NewFindUserInternalServerError creates FindUserInternalServerError with default headers values
func NewFindUserInternalServerError() *FindUserInternalServerError {

	return &FindUserInternalServerError{}
}

// WriteResponse to the client
func (o *FindUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
