// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// NewPasswordOKCode is the HTTP code returned for type NewPasswordOK
const NewPasswordOKCode int = 200

/*NewPasswordOK successful operation

swagger:response newPasswordOK
*/
type NewPasswordOK struct {
}

// NewNewPasswordOK creates NewPasswordOK with default headers values
func NewNewPasswordOK() *NewPasswordOK {

	return &NewPasswordOK{}
}

// WriteResponse to the client
func (o *NewPasswordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// NewPasswordInternalServerErrorCode is the HTTP code returned for type NewPasswordInternalServerError
const NewPasswordInternalServerErrorCode int = 500

/*NewPasswordInternalServerError internal error

swagger:response newPasswordInternalServerError
*/
type NewPasswordInternalServerError struct {
}

// NewNewPasswordInternalServerError creates NewPasswordInternalServerError with default headers values
func NewNewPasswordInternalServerError() *NewPasswordInternalServerError {

	return &NewPasswordInternalServerError{}
}

// WriteResponse to the client
func (o *NewPasswordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
