// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

/*NewPasswordDefault successful operation

swagger:response newPasswordDefault
*/
type NewPasswordDefault struct {
	_statusCode int
}

// NewNewPasswordDefault creates NewPasswordDefault with default headers values
func NewNewPasswordDefault(code int) *NewPasswordDefault {
	if code <= 0 {
		code = 500
	}

	return &NewPasswordDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the new password default response
func (o *NewPasswordDefault) WithStatusCode(code int) *NewPasswordDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the new password default response
func (o *NewPasswordDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *NewPasswordDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
