// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/jacygao/auth/models"
)

// NewSignupUserParams creates a new SignupUserParams object
// no default values defined in spec.
func NewSignupUserParams() SignupUserParams {

	return SignupUserParams{}
}

// SignupUserParams contains all the bound params for the signup user operation
// typically these are obtained from a http.Request
//
// swagger:parameters SignupUser
type SignupUserParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Sign up a new user
	  Required: true
	  In: body
	*/
	Body *models.UserSignupRequets
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSignupUserParams() beforehand.
func (o *SignupUserParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.UserSignupRequets
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
