// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// VerifyUserOKCode is the HTTP code returned for type VerifyUserOK
const VerifyUserOKCode int = 200

/*VerifyUserOK Successful Operation

swagger:response verifyUserOK
*/
type VerifyUserOK struct {
}

// NewVerifyUserOK creates VerifyUserOK with default headers values
func NewVerifyUserOK() *VerifyUserOK {

	return &VerifyUserOK{}
}

// WriteResponse to the client
func (o *VerifyUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// VerifyUserBadRequestCode is the HTTP code returned for type VerifyUserBadRequest
const VerifyUserBadRequestCode int = 400

/*VerifyUserBadRequest Invalid user supplied

swagger:response verifyUserBadRequest
*/
type VerifyUserBadRequest struct {
}

// NewVerifyUserBadRequest creates VerifyUserBadRequest with default headers values
func NewVerifyUserBadRequest() *VerifyUserBadRequest {

	return &VerifyUserBadRequest{}
}

// WriteResponse to the client
func (o *VerifyUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// VerifyUserNotFoundCode is the HTTP code returned for type VerifyUserNotFound
const VerifyUserNotFoundCode int = 404

/*VerifyUserNotFound User not found

swagger:response verifyUserNotFound
*/
type VerifyUserNotFound struct {
}

// NewVerifyUserNotFound creates VerifyUserNotFound with default headers values
func NewVerifyUserNotFound() *VerifyUserNotFound {

	return &VerifyUserNotFound{}
}

// WriteResponse to the client
func (o *VerifyUserNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
