// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AutheticateProfileOKCode is the HTTP code returned for type AutheticateProfileOK
const AutheticateProfileOKCode int = 200

/*AutheticateProfileOK Successful Operation

swagger:response autheticateProfileOK
*/
type AutheticateProfileOK struct {
}

// NewAutheticateProfileOK creates AutheticateProfileOK with default headers values
func NewAutheticateProfileOK() *AutheticateProfileOK {

	return &AutheticateProfileOK{}
}

// WriteResponse to the client
func (o *AutheticateProfileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AutheticateProfileBadRequestCode is the HTTP code returned for type AutheticateProfileBadRequest
const AutheticateProfileBadRequestCode int = 400

/*AutheticateProfileBadRequest Invalid user supplied

swagger:response autheticateProfileBadRequest
*/
type AutheticateProfileBadRequest struct {
}

// NewAutheticateProfileBadRequest creates AutheticateProfileBadRequest with default headers values
func NewAutheticateProfileBadRequest() *AutheticateProfileBadRequest {

	return &AutheticateProfileBadRequest{}
}

// WriteResponse to the client
func (o *AutheticateProfileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// AutheticateProfileInternalServerErrorCode is the HTTP code returned for type AutheticateProfileInternalServerError
const AutheticateProfileInternalServerErrorCode int = 500

/*AutheticateProfileInternalServerError internal error

swagger:response autheticateProfileInternalServerError
*/
type AutheticateProfileInternalServerError struct {
}

// NewAutheticateProfileInternalServerError creates AutheticateProfileInternalServerError with default headers values
func NewAutheticateProfileInternalServerError() *AutheticateProfileInternalServerError {

	return &AutheticateProfileInternalServerError{}
}

// WriteResponse to the client
func (o *AutheticateProfileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
