// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddNoteRequest add note request
//
// swagger:model AddNoteRequest
type AddNoteRequest struct {

	// body
	Body string `json:"body,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this add note request
func (m *AddNoteRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddNoteRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddNoteRequest) UnmarshalBinary(b []byte) error {
	var res AddNoteRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
