// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserVerifyRequest user verify request
//
// swagger:model UserVerifyRequest
type UserVerifyRequest struct {

	// code
	Code string `json:"code,omitempty"`

	// email
	Email string `json:"email,omitempty"`
}

// Validate validates this user verify request
func (m *UserVerifyRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserVerifyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserVerifyRequest) UnmarshalBinary(b []byte) error {
	var res UserVerifyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
